export const products = [
  {
    slug: 'aceh-gayo',
    name: 'Aceh Gayo',
    origin: 'Gayo Highlands, Aceh',
    description: 'A rich, full-bodied coffee with earthy notes of dark chocolate, cedar, and a hint of spice. Known for its smooth finish and low acidity, making it a classic Indonesian favorite.',
    price: 120000,
    image: 'https://placehold.co/800x800.png',
    aiHint: 'coffee beans bag',
    rating: 4.8,
    reviews: 125,
    tags: ['Earthy', 'Spicy', 'Full Body'],
    roast: 'Medium-Dark',
  },
  {
    slug: 'bali-kintamani',
    name: 'Bali Kintamani',
    origin: 'Kintamani Highlands, Bali',
    description: 'A smooth, sweet coffee with a clean finish and bright, citrusy undertones. Grown on volcanic soil alongside citrus fruits, which imparts a unique fruity aroma and flavor.',
    price: 135000,
    image: 'https://placehold.co/800x800.png',
    aiHint: 'bali landscape',
    rating: 4.9,
    reviews: 98,
    tags: ['Fruity', 'Citrus', 'Clean'],
    roast: 'Medium',
  },
  {
    slug: 'flores-bajawa',
    name: 'Flores Bajawa',
    origin: 'Bajawa, Flores',
    description: 'A complex coffee with beautiful floral aromas, sweet chocolate notes, and a syrupy, lingering body. The unique terroir of Flores gives this coffee a truly memorable character.',
    price: 150000,
    image: 'https://placehold.co/800x800.png',
    aiHint: 'indonesian flowers',
    rating: 4.7,
    reviews: 82,
    tags: ['Floral', 'Chocolate', 'Syrupy'],
    roast: 'Medium',
  },
  {
    slug: 'sumatra-mandheling',
    name: 'Sumatra Mandheling',
    origin: 'Mandailing, Sumatra',
    description: 'Famously smooth and heavy-bodied, this coffee presents deep, resonant notes of tobacco, dark cocoa, and a whisper of tropical fruit. A truly classic and satisfying cup.',
    price: 125000,
    image: 'https://placehold.co/800x800.png',
    aiHint: 'sumatra jungle',
    rating: 4.8,
    reviews: 110,
    tags: ['Full Body', 'Earthy', 'Complex'],
    roast: 'Dark',
  },
  {
    slug: 'toraja-kalosi',
    name: 'Toraja Kalosi',
    origin: 'Tana Toraja, Sulawesi',
    description: 'Well-balanced with a velvety body and notes of ripe fruit and dark chocolate. It has a vibrant yet low-toned acidity, making it a delightfully complex and clean coffee.',
    price: 140000,
    image: 'https://placehold.co/800x800.png',
    aiHint: 'sulawesi mountains',
    rating: 4.9,
    reviews: 102,
    tags: ['Balanced', 'Chocolate', 'Fruity'],
    roast: 'Medium-Dark',
  },
  {
    slug: 'java-preanger',
    name: 'Java Preanger',
    origin: 'West Java',
    description: 'One of the world\'s oldest coffee cultivation areas. This coffee offers a medium body, a mild acidity, and a smooth, clean taste with a sweet, slightly herbaceous finish.',
    price: 130000,
    image: 'https://placehold.co/800x800.png',
    aiHint: 'java coffee plantation',
    rating: 4.6,
    reviews: 75,
    tags: ['Smooth', 'Sweet', 'Herbal'],
    roast: 'Medium',
  },
];
